rm(list=ls())
wage95 <- read.csv("output95_update.csv",header=TRUE)

wage95_age <- lm(LNWAGE~AGE,data=wage95)
summary(wage95_age)
wage95_educ <- lm(LNWAGE~EDUC,data=wage95)
summary(wage95_educ)
wage95_potexp <- lm(LNWAGE~EXPER,data=wage95)
summary(wage95_potexp)

wage95_age_educ <- lm(LNWAGE~AGE+EDUC,data=wage95)
summary(wage95_age_educ)
wage95_educ_exper <- lm(LNWAGE~EDUC+EXPER,data=wage95)
summary(wage95_educ_exper)
wage95_age_exper <- lm(LNWAGE~AGE+EXPER,data=wage95)
summary(wage95_age_exper)

wage95_union <- lm(LNWAGE~UNION,data=wage95)
summary(wage95_union)
wage95_female <- lm(LNWAGE~FEMALE,data=wage95)
summary(wage95_female)
wage95_nonwhite <- lm(LNWAGE~NONWHITE,data=wage95)
summary(wage95_nonwhite)

wage95_union_female <- lm(LNWAGE~UNION+FEMALE,data=wage95)
summary(wage95_union_female)
wage95_union_nonwhite <- lm(LNWAGE~UNION+NONWHITE,data=wage95)
summary(wage95_union_nonwhite)
wage95_female_nonwhite <- lm(LNWAGE~FEMALE+NONWHITE,data=wage95)
summary(wage95_female_nonwhite)

wage95_indicatorvars <- lm(LNWAGE~UNION+FEMALE+NONWHITE,data=wage95)
summary(wage95_indicatorvars)

wage95_indicatorvars_age <- lm(LNWAGE~UNION+FEMALE+NONWHITE+AGE,data=wage95)
summary(wage95_indicatorvars_age)
wage95_indicatorvars_potexp <- lm(LNWAGE~UNION+FEMALE+NONWHITE+EXPER,data=wage95)
summary(wage95_indicatorvars_potexp)
wage95_indicatorvars_educ <- lm(LNWAGE~UNION+FEMALE+NONWHITE+EDUC,data=wage95)
summary(wage95_indicatorvars_educ)

wage95_age_educ_union <- lm(LNWAGE~AGE+EDUC+UNION,data=wage95)
summary(wage95_age_educ_union)
wage95_age_educ_female <- lm(LNWAGE~AGE+EDUC+FEMALE,data=wage95)
summary(wage95_age_educ_female)
wage95_age_educ_nonwhite <- lm(LNWAGE~AGE+EDUC+NONWHITE,data=wage95)
summary(wage95_age_educ_nonwhite)

wage95_age_educ_union_female <- lm(LNWAGE~AGE+EDUC+UNION+FEMALE,data=wage95)
summary(wage95_age_educ_union_female)
wage95_age_educ_union_nonwhite <- lm(LNWAGE~AGE+EDUC+UNION+NONWHITE,data=wage95)
summary(wage95_age_educ_union_nonwhite)
wage95_age_educ_female_nonwhite <- lm(LNWAGE~AGE+EDUC+FEMALE+NONWHITE,data=wage95)
summary(wage95_age_educ_female_nonwhite)

wage95_educ_exper_union <- lm(LNWAGE~EDUC+EXPER+UNION,data=wage95)
summary(wage95_educ_exper_union)
wage95_educ_exper_female <- lm(LNWAGE~EDUC+EXPER+FEMALE,data=wage95)
summary(wage95_educ_exper_female)
wage95_educ_exper_nonwhite <- lm(LNWAGE~EDUC+EXPER+NONWHITE,data=wage95)
summary(wage95_educ_exper_nonwhite)

wage95_educ_exper_union_female <- lm(LNWAGE~EDUC+EXPER+UNION+FEMALE,data=wage95)
summary(wage95_educ_exper_union_female)
wage95_educ_exper_union_nonwhite <- lm(LNWAGE~EDUC+EXPER+UNION+NONWHITE,data=wage95)
summary(wage95_educ_exper_union_nonwhite)
wage95_educ_exper_female_nonwhite <- lm(LNWAGE~EDUC+EXPER+FEMALE+NONWHITE,data=wage95)
summary(wage95_educ_exper_female_nonwhite)

wage95_age_exper_union <- lm(LNWAGE~AGE+EXPER+UNION,data=wage95)
summary(wage95_age_exper_union)
wage95_age_exper_female <- lm(LNWAGE~AGE+EXPER+FEMALE,data=wage95)
summary(wage95_age_exper_female)
wage95_age_exper_nonwhite <- lm(LNWAGE~AGE+EXPER+NONWHITE,data=wage95)
summary(wage95_age_exper_nonwhite)

wage95_age_exper_union_female <- lm(LNWAGE~AGE+EXPER+UNION+FEMALE,data=wage95)
summary(wage95_age_exper_union_female)
wage95_age_exper_union_nonwhite <- lm(LNWAGE~AGE+EXPER+UNION+NONWHITE,data=wage95)
summary(wage95_age_exper_union_nonwhite)
wage95_age_exper_female_nonwhite <- lm(LNWAGE~AGE+EXPER+FEMALE+NONWHITE,data=wage95)
summary(wage95_age_exper_female_nonwhite)

wage95_fullreg <- lm(LNWAGE~AGE+EXPER+UNION+FEMALE+NONWHITE,data=wage95)
summary(wage95_fullreg)