rm(list=ls())
wage04 <- read.csv("output04_update.csv",header=TRUE)

wage04_age <- lm(LNWAGE~AGE,data=wage04)
summary(wage04_age)
wage04_educ <- lm(LNWAGE~EDUC,data=wage04)
summary(wage04_educ)
wage04_potexp <- lm(LNWAGE~EXPER,data=wage04)
summary(wage04_potexp)

wage04_age_educ <- lm(LNWAGE~AGE+EDUC,data=wage04)
summary(wage04_age_educ)
wage04_educ_exper <- lm(LNWAGE~EDUC+EXPER,data=wage04)
summary(wage04_educ_exper)
wage04_age_exper <- lm(LNWAGE~AGE+EXPER,data=wage04)
summary(wage04_age_exper)

wage04_union <- lm(LNWAGE~UNION,data=wage04)
summary(wage04_union)
wage04_female <- lm(LNWAGE~FEMALE,data=wage04)
summary(wage04_female)
wage04_nonwhite <- lm(LNWAGE~NONWHITE,data=wage04)
summary(wage04_nonwhite)

wage04_union_female <- lm(LNWAGE~UNION+FEMALE,data=wage04)
summary(wage04_union_female)
wage04_union_nonwhite <- lm(LNWAGE~UNION+NONWHITE,data=wage04)
summary(wage04_union_nonwhite)
wage04_female_nonwhite <- lm(LNWAGE~FEMALE+NONWHITE,data=wage04)
summary(wage04_female_nonwhite)

wage04_indicatorvars <- lm(LNWAGE~UNION+FEMALE+NONWHITE,data=wage04)
summary(wage04_indicatorvars)

wage04_indicatorvars_age <- lm(LNWAGE~UNION+FEMALE+NONWHITE+AGE,data=wage04)
summary(wage04_indicatorvars_age)
wage04_indicatorvars_potexp <- lm(LNWAGE~UNION+FEMALE+NONWHITE+EXPER,data=wage04)
summary(wage04_indicatorvars_potexp)
wage04_indicatorvars_educ <- lm(LNWAGE~UNION+FEMALE+NONWHITE+EDUC,data=wage04)
summary(wage04_indicatorvars_educ)

wage04_age_educ_union <- lm(LNWAGE~AGE+EDUC+UNION,data=wage04)
summary(wage04_age_educ_union)
wage04_age_educ_female <- lm(LNWAGE~AGE+EDUC+FEMALE,data=wage04)
summary(wage04_age_educ_female)
wage04_age_educ_nonwhite <- lm(LNWAGE~AGE+EDUC+NONWHITE,data=wage04)
summary(wage04_age_educ_nonwhite)

wage04_age_educ_union_female <- lm(LNWAGE~AGE+EDUC+UNION+FEMALE,data=wage04)
summary(wage04_age_educ_union_female)
wage04_age_educ_union_nonwhite <- lm(LNWAGE~AGE+EDUC+UNION+NONWHITE,data=wage04)
summary(wage04_age_educ_union_nonwhite)
wage04_age_educ_female_nonwhite <- lm(LNWAGE~AGE+EDUC+FEMALE+NONWHITE,data=wage04)
summary(wage04_age_educ_female_nonwhite)

wage04_educ_exper_union <- lm(LNWAGE~EDUC+EXPER+UNION,data=wage04)
summary(wage04_educ_exper_union)
wage04_educ_exper_female <- lm(LNWAGE~EDUC+EXPER+FEMALE,data=wage04)
summary(wage04_educ_exper_female)
wage04_educ_exper_nonwhite <- lm(LNWAGE~EDUC+EXPER+NONWHITE,data=wage04)
summary(wage04_educ_exper_nonwhite)

wage04_educ_exper_union_female <- lm(LNWAGE~EDUC+EXPER+UNION+FEMALE,data=wage04)
summary(wage04_educ_exper_union_female)
wage04_educ_exper_union_nonwhite <- lm(LNWAGE~EDUC+EXPER+UNION+NONWHITE,data=wage04)
summary(wage04_educ_exper_union_nonwhite)
wage04_educ_exper_female_nonwhite <- lm(LNWAGE~EDUC+EXPER+FEMALE+NONWHITE,data=wage04)
summary(wage04_educ_exper_female_nonwhite)

wage04_age_exper_union <- lm(LNWAGE~AGE+EXPER+UNION,data=wage04)
summary(wage04_age_exper_union)
wage04_age_exper_female <- lm(LNWAGE~AGE+EXPER+FEMALE,data=wage04)
summary(wage04_age_exper_female)
wage04_age_exper_nonwhite <- lm(LNWAGE~AGE+EXPER+NONWHITE,data=wage04)
summary(wage04_age_exper_nonwhite)

wage04_age_exper_union_female <- lm(LNWAGE~AGE+EXPER+UNION+FEMALE,data=wage04)
summary(wage04_age_exper_union_female)
wage04_age_exper_union_nonwhite <- lm(LNWAGE~AGE+EXPER+UNION+NONWHITE,data=wage04)
summary(wage04_age_exper_union_nonwhite)
wage04_age_exper_female_nonwhite <- lm(LNWAGE~AGE+EXPER+FEMALE+NONWHITE,data=wage04)
summary(wage04_age_exper_female_nonwhite)

wage04_fullreg <- lm(LNWAGE~AGE+EXPER+UNION+FEMALE+NONWHITE,data=wage04)
summary(wage04_fullreg)